name: Deploy all services (ECS)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Force new deployment for catalogs
        run: |
          aws ecs update-service \
            --cluster EXAMEN2_CLUSTER \
            --service catalogs-service \
            --force-new-deployment

      - name: Force new deployment for sales
        run: |
          aws ecs update-service \
            --cluster EXAMEN2_CLUSTER \
            --service sales-service \
            --force-new-deployment

      - name: Force new deployment for notifications
        run: |
          aws ecs update-service \
            --cluster EXAMEN2_CLUSTER \
            --service notifications-service \
            --force-new-deployment
